### Pandas DataFrame

A Pandas DataFrame is a two-dimensional table-like structure in Python where data is arranged in rows and columns. It’s one of the most commonly used tools for handling data and makes it easy to organize, analyze and manipulate data. It can store different types of data such as numbers, text and dates across its columns. The main parts of a DataFrame are:

- Data: Actual values in the table.
- Rows: Labels that identify each row.
- Columns: Labels that define each data category.

In [ ]:
#      Country      Capital      Population
# 0    Canada       Ottawa       37742154
# 1    Australia    Canberra     25499884
# 2    UK           London       67886011
# 3    Brazil       Brasília     212559417

### In the above case
- `Country`, `Capital` and `Population` are the column names.
- Each row represents a record, with the index value on the left. The index values are auto-assigned starting from 0.
- Each column contains data of the same type. For instance, `Country` and `Capital` contain strings, and `Population` contains integers.

### Create a Pandas DataFrame
#### We can create a Pandas DataFrame in the following ways:

- Using Python Dictionary
- Using Python List
- From a File
- Creating an Empty DataFrame

### Pandas DataFrame Using Python Dictionary

In [5]:
import pandas as pd

# create a dictionary
data = {'Name': ['John', 'Alice', 'Bob'],
       'Age': [25, 30, 35],
       'City': ['New York', 'London', 'Paris']}


# # create a dataframe from the dictionary
df = pd.DataFrame(data)

print(type(df))

<class 'pandas.core.frame.DataFrame'>

### Pandas DataFrame Using Python List

In [4]:
import pandas as pd

# create a two-dimensional list
data = [
       ['John', 25, 'New York'],
       ['Alice', 30, 'London'],
       ['Bob', 35, 'Paris']
]

# create a DataFrame from the list
df = pd.DataFrame(data)

print(type(df))

<class 'pandas.core.frame.DataFrame'>

### Pandas DataFrame From a File

In [ ]:
# .csv, .xlsx, .pdf , .py, .txt , .ipynb

In [6]:
import pandas as pd

# load data from a CSV file
df = pd.read_csv('/Users/sahilnagpal/Library/Application Support/JetBrains/DataSpell2025.3/projects/workspace/data/tips.csv')

df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### Create an Empty DataFrame

In [8]:
import pandas as pd

# create an empty DataFrame
df = pd.DataFrame()

Empty DataFrame
Columns: []
Index: []