### Pandas DataFrame

A Pandas DataFrame is a two-dimensional table-like structure in Python where data is arranged in rows and columns. It’s one of the most commonly used tools for handling data and makes it easy to organize, analyze and manipulate data. It can store different types of data such as numbers, text and dates across its columns. The main parts of a DataFrame are:

- Data: Actual values in the table.
- Rows: Labels that identify each row.
- Columns: Labels that define each data category.

In [ ]:
#      Country      Capital      Population
# 0    Canada       Ottawa       37742154
# 1    Australia    Canberra     25499884
# 2    UK           London       67886011
# 3    Brazil       Brasília     212559417

### In the above case
- `Country`, `Capital` and `Population` are the column names.
- Each row represents a record, with the index value on the left. The index values are auto-assigned starting from 0.
- Each column contains data of the same type. For instance, `Country` and `Capital` contain strings, and `Population` contains integers.

### Create a Pandas DataFrame
#### We can create a Pandas DataFrame in the following ways:

- Using Python Dictionary
- Using Python List
- From a File
- Creating an Empty DataFrame

### Pandas DataFrame Using Python Dictionary

In [1]:
import pandas as pd

# create a dictionary
data = {
       'Name': ['John', 'Alice', 'Bob'],
       'Age': [25, 30, 35],
       'City': ['New York', 'London','Paris']
}


# # create a dataframe from the dictionary
df = pd.DataFrame(data)

df

    Name  Age      City
0   John   25  New York
1  Alice   30    London
2    Bob   35     Paris

### Pandas DataFrame Using Python List

In [4]:
import pandas as pd

# create a two-dimensional list
data = [
       ['John', 25, 'New York'],
       ['Alice', 30, 'London'],
       ['Sahil', 35, 'Paris']
]

# create a DataFrame from the list
df = pd.DataFrame(data)

df

       0   1         2
0   John  25  New York
1  Alice  30    London
2  Sahil  35     Paris

### Pandas DataFrame From a File

In [5]:
import pandas as pd


# load data from a CSV file
df = pd.read_csv('/Users/sahilnagpal/Desktop/Pragra-Python/data/titanic.csv')
# path of the csv file

df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

### Create an Empty DataFrame

In [7]:
import pandas as pd

# create an empty DataFrame
df = pd.DataFrame() # empty DataFrame

# logging

pandas.core.frame.DataFrame